version: '3.1'

volumes:
  media:

networks:
  mynetwork:
    driver: bridge

services:
  backend:
    env_file:
      - frontend/.env
    build: ./backend
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
      - media:/backend/media/images
    environment:
      - DEBUG=True
      - ENVIRONMENT=local
    networks:
      - mynetwork

  frontend:
    env_file:
      - frontend/.env
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/frontend
      - ./frontend/.next:/frontend/.next
      - media:/frontend/public/media/images
    networks:
      - mynetwork
    tty: true
    stdin_open: true