version: '3.1'

volumes:
  media:
  static:

networks:
  mynetwork:
    driver: bridge

services:
  backend:
    env_file:
      - frontend/.env
    restart: unless-stopped 
    build: ./backend
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    ports:
      - "8000:8000"
    volumes:
      - static:/backend/static_root
      - media:/backend/media
    environment:
      - DEBUG=False
      - ENVIRONMENT=production
    networks:
      - mynetwork
      

  frontend:
    restart: unless-stopped
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - mynetwork
    env_file:
      - frontend/.env
    volumes:
      - media:/frontend/public/media

  nginx:
      image: nginx:alpine
      restart: unless-stopped
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
        - /etc/ssl/certs:/etc/ssl/certs:ro
        - /etc/ssl/private:/etc/ssl/private:ro
        - static:/backend/static_root
        - media:/backend/media
      networks:
        - mynetwork
      depends_on:
        - frontend
        - backend