# Generated by Django 4.2.4 on 2023-11-01 10:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(blank=True, max_length=255, validators=[django.core.validators.URLValidator()])),
                ('twitter', models.CharField(blank=True, max_length=255, validators=[django.core.validators.URLValidator()])),
                ('instagram', models.CharField(blank=True, max_length=255, validators=[django.core.validators.URLValidator()])),
                ('threads', models.CharField(blank=True, max_length=255, validators=[django.core.validators.URLValidator()])),
                ('youtube', models.CharField(blank=True, max_length=255, validators=[django.core.validators.URLValidator()])),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
