# Generated by Django 4.2.4 on 2023-11-06 11:01

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_social'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='social',
            options={'ordering': ('order',)},
        ),
        migrations.AlterField(
            model_name='social',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Product Title')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Product URL')),
                ('langslug', models.CharField(blank=True, max_length=255, verbose_name='Translation Link')),
                ('pageinfo', models.TextField(blank=True, verbose_name='Product Description')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Product Content')),
                ('shoplink', models.CharField(blank=True, max_length=255, verbose_name='Shop Link')),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('lang', models.CharField(blank=True, choices=[('en', 'English'), ('tr', 'Turkish')], default='en', max_length=7, verbose_name='Language')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('categories', models.ManyToManyField(blank=True, to='content.category')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_selected_image', to='content.image', verbose_name='Selected Cover Image')),
                ('images', models.ManyToManyField(blank=True, related_name='product_images', to='content.image', verbose_name='Select Content Images')),
                ('tags', models.ManyToManyField(blank=True, to='content.tag')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
