# Generated by Django 4.2.4 on 2023-11-06 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_social_options_alter_social_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
    ]
