# Generated by Django 4.2.4 on 2023-11-07 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_remove_product_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='posts',
        ),
        migrations.AddField(
            model_name='homepage',
            name='products',
            field=models.ManyToManyField(blank=True, to='content.product', verbose_name='Select Products to display on Homepage'),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
