# Generated by Django 4.2.4 on 2023-11-07 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_remove_homepage_posts_homepage_products_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='lang',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('tr', 'Turkish')], default='en', max_length=7, verbose_name='Language'),
        ),
    ]
