# Generated by Django 4.2.4 on 2023-11-07 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_category_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_image', to='content.image', verbose_name='Selected Image'),
        ),
        migrations.AddField(
            model_name='category',
            name='langslug',
            field=models.CharField(blank=True, max_length=255, verbose_name='Translation Link'),
        ),
    ]
