# Generated by Django 4.2.4 on 2023-11-08 07:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_category_image_category_langslug'),
    ]

    operations = [
        migrations.AddField(
            model_name='social',
            name='linkedin',
            field=models.CharField(blank=True, max_length=255, validators=[django.core.validators.URLValidator()]),
        ),
    ]
