# Generated by Django 4.2.4 on 2023-11-08 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_social_linkedin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='social',
            name='threads',
        ),
    ]
