# Generated by Django 4.2.4 on 2023-12-01 17:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_alter_category_options_category_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Product Content'),
        ),
    ]
